### PR TITLE
feat: Add automation for feature flag data schema addition process

### PR DESCRIPTION
**Pull request by thogarty**
* Add GHA jobs for automating the repository based on data_schema additions
* Update scripts to account for feature flags for data_schemas and their internal events/metrics/alerts
* Run automation locally to account for updates to catalog.json, README.md, and DataLoader* files

### CODE REVIEW

**Review by ryli17 — COMMENTED** [review]
@thogarty , Thank you very much for the automation!
One comments: We don't have `alertNames`. Alert is same as an event. It is identified by eventType. Therefore, no need to add particular section in each json file, nor in the script.

**Comment by thogarty** [comment]
> @thogarty , Thank you very much for the automation! One comments: We don't have `alertNames`. Alert is same as an event. It is identified by eventType. Therefore, no need to add particular section in each json file, nor in the script.

That's a good point. I only added it because Avinash wanted flexibility in place in case teams outside of Fabric and DIGIN didn't treat their alerts in the same way. So that they could treat it similarly to the metrics where there's one alert event type with several supported alertNames.

@anchala71 , could use your input with that one.

**Comment by yetang-equinix** [comment]
@thogarty , why do we use metricNames instead of metricTypes? It is "Metric Types" in README.

**Comment by thogarty** [comment]
@anchala71 , need your input on alertNames. We need this PR to be merged before the Data Schema Registration training session this evening.

**Review by ryli17 — APPROVED** [review]

**Comment by thogarty** [comment]
Merging this PR. Following up with a second to replace `Metric Types` with `Metric Names` in README.md and to add:
* Version bump GHA
* CONTRIBUTING.md for data schema registration

**Pull request merged**
